enable-magisk-update = false

[TikTok]
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
build-mode = "apk"
arch = "both"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
excluded-patches = "'Show seekbar'"
